name: Integration Test

on:
  push:
    paths:
      - "viral_usher/**"
      - "tests/test_data/**"
      - "Dockerfile"
      - "pyproject.toml"
      - ".github/workflows/integration-test.yml"
  pull_request:
    paths:
      - "viral_usher/**"
      - "tests/test_data/**"
      - "Dockerfile"
      - "pyproject.toml"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        tags: angiehinrichs/viral_usher:development
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"

    - name: Install viral_usher
      run: |
        python -m pip install --upgrade pip
        pip install -e .

  test:
    runs-on: ubuntu-latest
    needs: setup
    strategy:
      matrix:
        test_name: ['no_genbank', 'prrsv2_nextclade', 'prrsv2_nextclade_extra_fasta', 'ehdv_4', 'ehdv_4_viral_usher_trees', 'ehdv_4_extra_fasta', 'ehdv_4_extra_fasta_metadata']
      max-parallel: 5
    steps:
    - name: Run test script
      run: |
        mkdir -p tests/test_data/output
        bash tests/test_${{ matrix.test_name }}.sh tests/test_data/output
        rm -rf tests/test_data/output
